title: Hossein Basereh Taramsari
logo: /assets/img/CR.png
description: Ph.D. Candidate in Engineering Management with M.Sc. in Mechanical Engineering
# show_downloads: true
theme: jekyll-theme-cayman
