title: Hossein Basereh Taramsari
logo: /assets/img/Hpic.png
description: Ph.D. Candidate in Engineering Management, Contact: [basereh.hossein@outlook.com](mailto:basereh.hossein@outlook.com) | [LinkedIn](https://www.linkedin.com/in/hossein-basereh), Address: Jersey City, NJ, United States
# show_downloads: true
theme: jekyll-theme-minimal
